### ISSUE TITLE
Arreglar márgenes de contenedor general y tamaño de menú en pantallas grandes

### ISSUE THREAD

**Issue by anattolia** [enflujo/arca-www#116]
Con el arreglo de pantallas gigantes creo que se dañaron los márgenes y el tamaño del menú de las pantallas grandes. En mi portátil se ve así: 

![Captura de pantalla_20230227_074857](https://user-images.githubusercontent.com/5365329/221723637-d73d52df-79cd-486e-8ad9-274aeea05e1e.png)

**Comment by 1cgonza** [comment]
Resuelto con [b6ed839](https://github.com/enflujo/arca-www/commit/b6ed839bfb6bf06402893ef11cf37b830855affd)
