### ISSUE TITLE
💥 Error: 404

### ISSUE THREAD

**Issue by HoyosQ** [enflujo/arca-www#125]
Crear componente (no se si se llama de esta manera...) para pagina de error 404

**Comment by 1cgonza** [comment]
Este existe pero no tiene gran cosa de momento, el archivo es: `./error.vue` que ahora simplemente imprime **Error 404**- Esto es lo que tiene:

```vue
<template>
  <div class="contenedor">
    <div class="centrar-contenido">
      <h1>ERROR 404</h1>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped></style>
``` 

Se puede diseñar algo más interesante, @HoyosQ piensa que puede ir acá y lo empiezas a trabajar. 

Por ejemplo, cambia lo que esta ahora a esto:

```vue
<script setup>
const props = defineProps({
  error: Object,
});
</script>

<template>
  <div id="contenedor">
    <h1>ERROR 404 :(</h1>
  </div>
</template>

<style lang="scss" scoped>
#contenedor {
  background-color: black;
  color: white;
  padding: 5em;
  text-align: center;
  min-height: 100vh;
}
</style>
```

**Comment by 1cgonza** [comment]
Resuelto en [2a34cb5](https://github.com/enflujo/arca-www/commit/2a34cb544182f1e194564e94a8155a0ef6d4d1a8)
