### ISSUE TITLE
Diseñar página de obra individual

### ISSUE THREAD

**Issue by anattolia** [enflujo/arca-www#130]
Diseñar la página de obra individual 🎨

**Comment by Juliansintilde** [comment]
Presento el primer boceto del diseño de la vista de obras individuales:

![pantalla- vista - obraobra-limpio](https://user-images.githubusercontent.com/42554838/232136131-0201cf32-e780-4133-b0f1-83b90c8eed69.jpg)

Aquí con el esqueleto detrás:

![pantalla- vista - obraobra-estructura](https://user-images.githubusercontent.com/42554838/232136164-99f7db0d-5ec4-46d3-bf9a-ff31d8b7d056.jpg)


Aquí el esqueleto solo:

![pantalla- vista - obraobra-estructura-sola](https://user-images.githubusercontent.com/42554838/232136179-be877afb-26e1-4f86-ab69-039099b38141.jpg)


Esqueleto con algo más de detalle de cómo funcionan las proporciones:

![pantalla- vista - obraobra-estructura-guias](https://user-images.githubusercontent.com/42554838/232136198-9a514827-cb44-4f4e-b16c-479021f5d294.jpg)


Por ahora estamos usando el color **rojoCerezo** y el azul **profundidad**
