### ISSUE TITLE
Arreglar enlaces en Archivo-Ubicación

### ISSUE THREAD

**Issue by anattolia** [enflujo/arca-www#146]
En este momento los enlaces de Ubicaciones desde las vistas de ABC y colombinas mandan a /ubicaciones/pais desde los países y fallan. No lo arreglo aún porque hay que decidir cómo elegir si filtramos por países, ciudades y ubicaciones y, según dónde esté, cambiar los enlaces.

**Comment by 1cgonza** [comment]
Resuelto en [7b26615](https://github.com/enflujo/arca-www/commit/7b266152bbdd57f1723dcbbe5e76dc7a5a23d656)
