### ISSUE TITLE
Agregar a imagen individual galería de imágenes relacionadas

### ISSUE THREAD

**Issue by anattolia** [enflujo/arca-www#38]
Agregar a imagen individual galería de imágenes relacionadas: desarrollar lógica y diseño.

**Comment by 1cgonza** [comment]
@anattolia y @Juliansintilde coordinen ustedes a ver como proceder con esto y cuando lo tengan más claro, dividir este issue en partes que se van a hacer. Lo primero sería revisar el diseño que tenemos y ver que falta o como se va a cambiar si es el caso.
