### ISSUE TITLE
Agregar lógica a etiquetas de buscador

### ISSUE THREAD

**Issue by anattolia** [enflujo/arca-www#42]
Agregar lógica a etiquetas de buscador: aparecer y buscar al seleccionar, desaparecer y cambiar la búsqueda al cerrar.
Agregar un for para mostrar varias etiquetas.

**Comment by 1cgonza** [comment]
Este es importante pero toca agregar una aplicación adicional (`docker-compose`) para que las busquedas se administren desde una aplicación dedicada a eso.

Potenciales candidadatos para esto sería:
- [Meilisearch](https://www.meilisearch.com/)
- [Elasticsearch](https://www.elastic.co/es/)

Esta extensión de Directus puede ayudar a sincronizar las bases de datos.
- [searchsync](https://github.com/dimitrov-adrian/directus-extension-searchsync)
