### ISSUE TITLE
¿Cómo calcular el número de páginas de la galería?

### ISSUE THREAD

**Issue by anattolia** [enflujo/arca-www#44]
En galería pensar: ¿Cómo calcular el número de páginas para mostrar una lista de números?
Actualmente si hay menos de 100 obras, no muestra la lista. Si hay más, muestra una lista de 1 a 10. 
¿Quizás la cantidad total de imágenes por categoría es un dato que podría venir directamente de la base de datos?

**Comment by 1cgonza** [comment]
Ya está calculando bien en el componente `Cargador.vue`
