### ISSUE TITLE
Pasar información de "Sobre Arca" a Directus y quitar del html

### ISSUE THREAD

**Issue by anattolia** [enflujo/arca-www#54]

**Comment by 1cgonza** [comment]
El footer aún tiene información que toca pasar al CMS

**Comment by anattolia** [comment]
Ya está la información en el CMS pero no quedó en la última bd que mandó Camilo.

**Comment by 1cgonza** [comment]
Volverla a pasar al Directus que ya es, @anattolia puedes hacer esto para que el guardaescoba se conecte al tally y se llene la información en la página?
