### ISSUE TITLE
Agregar mapa a galería de imágenes

### ISSUE THREAD

**Issue by anattolia** [enflujo/arca-www#61]
Agregar un mapa a la galería de imágenes que muestre la ubicación de las obras seleccionadas

**Comment by 1cgonza** [comment]
Ah, nos toca entonces cambiar un poco la lógica del componente Mapa que tenemos ahora porque esta hecho muy especificamente para la sección de ubicaciones. Si separamos un poco las cosas se puede reutilizar pasandole props diferentes a los que tiene ahora.
