### ISSUE TITLE
Hacer mapa de urls de sitio actual

### ISSUE THREAD

**Issue by anattolia** [enflujo/arca-www#64]
Hacer mapa de urls del sitio actual de Arca http://artecolonialamericano.az.uniandes.edu.co:8080/

**Comment by 1cgonza** [comment]
:mouse: Quien tiene alma de ratón y hace esto? asistentes? alguno de nosotros?

**Comment by HoyosQ** [comment]
@1cgonza es esto algo con lo que podria ayudar?

**Comment by 1cgonza** [comment]
@HoyosQ Si! el archivo donde estamos creando el mapeo está en: https://github.com/enflujo/despliegue-arca/tree/main/fuente/urls

El ejercicio es ir a http://artecolonialamericano.az.uniandes.edu.co:8080/ y revisar los diferentes enlaces que están allí para ir relacionando donde queda esa información en el nuevo sitio.

**Comment by anattolia** [comment]
@1cgonza quiero recordar que antes de hacer todo el mapeo íbamos a pensar en la mejor forma de organizar el archivo para que sirviera de base para la automatización, y así no tener que hacer el trabajo más de una vez.

**Comment by 1cgonza** [comment]
Gracias @anattolia, @HoyosQ lo que puedes ir haciendo es el mapeo de las URLs de la pagina de antes y dejar vacío el del nuevo y lo llenamos cuando estemos listos. Igual ir adelantando la extracción de las URLs del sitio viejo es importante y nos sirve para que nos se quede nada por fuera en la nueva.
