### ISSUE TITLE
Crear páginas de galería para los distintos menús (filtros)

### ISSUE THREAD

**Issue by anattolia** [enflujo/arca-www#68]
Crear  páginas de galería para los distintos menús: gestos, categorías, etc.

**Comment by anattolia** [comment]
Jaime dijo: 

- Autores
- Categorías 
- Escenarios
- Técnicas
- Donantes
- Ubicación (museo/iglesia) ( O quizás países y dentro de países - Ciudad - Museo/Iglesia)
- Relatos Visuales
- Descriptores
- Objetos
- Gestos
- Cartela/filacteria
- Símbolos
- Características particulares
- Fechas (¿O una línea de tiempo que filtre dentro de la categoría seleccionada?)
- Fisiognómica (se puede quitar, si son demasiados)

Son muchos, no sé si vale la pena desplegar otro menú con todas las opciones o algo así

**Comment by 1cgonza** [comment]
> Jaime dijo:
> 
> * Autores
> * Categorías
> * Escenarios
> * Técnicas
> * Donantes
> * Ubicación (museo/iglesia) ( O quizás países y dentro de países - Ciudad - Museo/Iglesia)
> * Relatos Visuales
> * Descriptores
> * Objetos
> * Gestos
> * Cartela/filacteria
> * Símbolos
> * Características particulares
> * Fechas (¿O una línea de tiempo que filtre dentro de la categoría seleccionada?)
> * Fisiognómica (se puede quitar, si son demasiados)
> 
> Son muchos, no sé si vale la pena desplegar otro menú con todas las opciones o algo así

Bien! partamos de este para diseñar la interfaz y vamos viendo con los datos modelados como quedan estos menús.

**Comment by 1cgonza** [comment]
Lo resuelven caa5890c9a13368cf076f9287428fc6c11390c14 y 38f22b71a98d612fb8b445dd97d575503bd64b99.

Lo de la linea de tiempo debe ser un issue aparte.
