### ISSUE TITLE
Implementar hover destacado para galería 💅🏽

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/arca-www#89]
Hay dos opciones sobre las que se puede hacer un hover destacado, en una se hace un zoom y en la otra solo se resalta. 
Dejo a su consideración cuál les gusta más 😬

<img width="1920" alt="3_galeria_destacado_2" src="https://user-images.githubusercontent.com/42554838/215213835-2980f3d3-1ddf-4518-848b-06d4f8438334.png">
<img width="1920" alt="2_galeria_destacado_2" src="https://user-images.githubusercontent.com/42554838/215213963-163d51f3-d18f-4890-9538-8148fd815d78.png">

**Comment by HoyosQ** [comment]
@Juliansintilde descolonizate, no es hover, es **suspensión**.
